# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.12.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: Liquidsoap service template 🧴
reponame: template-service-liquidsoap
repourl: https://github.com/radio-aktywne/template-service-liquidsoap
templatename: liquidsoap
type: service
